eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/
server:
  port: 8083

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/laiyunxiang007/config
          searchPaths: democonfig/helloworldConfig,zuulconfig
          username: 294805447@qq.com
          password: az8247758
          default-label: master
  application:
    name: config-server

