server:
  port: 8082
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: peer2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://peer1:8081/eureka/
spring:
  application:
    name: eureka