server:
  port: 8086
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/
zuul:
  routes:
    eureka-client:
      path: /eureka-client/**
    ribbonClient:
      path: /ribbonClient/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
#  sensitive-headers: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8094/user
