server:
  port: 8086
spring:
  application:
    name: eureka-zuul
eureka:
  client:
    service-url:
      defaultZone: http://peer1:8081/eureka/,http://peer2:8082/eureka/
zuul:
  routes:
    eureka-client:
      path: /eureka-client/**
    ribbonClient:
      path: /ribbonClient/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
  ignored-services: '*'

  sensitive-headers: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 8000
  ConnectTimeout: 8000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 8000

security:
  oauth2:
    client:
      access-token-uri:  http://localhost:8094/oauth/token
      user-authorization-uri:
      client-id: eureka-zuul
      client-secret: thissecret
    resource:
      user-info-uri: http://localhost:8094/user
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS